id: PCEEB77B2
initial_creation_type: input
source_metadata:
  title: Abhisamayālaṃkāra Series
  language: bo
  description: 'Texts related to the Abhisamayālaṃkāra (mngon rtogs rgyan) or Clear
    Ornament of Realization, one of the Five Treatises of Maitreyanātha:'
  volume:
    ffc7c97261d14a1da20426938cd0b691:
      title: 'Words from the Lineage Masters to Clarify Maitreyanātha''s Vision: An
        Overview of the Perfection of Wisdom''s Ornament of Realization'
      parent: Commentaries
    5becb2d1810e437890d144ce3d1c7144:
      title: Prologue to Abhisamayālaṃkāra Commentary
      parent: Commentaries
    38e94f4baa214a4389d604f70ad0e285:
      title: A Preliminary to the Explanation of the Prajñāpāramitā
      parent: Commentaries
    ad3e97d949fe420a8412094ffe1dcfad:
      title: 'The Words of Jigme Chökyi Wangpo: A Commentary Presenting the Subject
        Matter of the Great Treatise Abhisamayālaṃkāra'
      parent: Commentaries
    989ebd1f559f49a2b6d3be56e2793c55:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Commentaries
    5ebf8e7714c74d079f896fe77a946971:
      title: The Eightfold Nature of Profundity from the Abhisamayālaṃkāra
      parent: Notes
created_at: '2022-03-01T02:29:29.033475'
last_modified_at: '2022-03-01T02:29:29.033479'
statistics:
  total_words: 29134
  total_non_words: 2840
quality:
  non_words_ratio: 0.1
